use utilities_locator;
INSERT INTO metro_station VALUES
('Attiguppe', 'Purple Line', 'Elevated', 'AGPP'),
('Baiyappanahalli', 'Purple Line', 'At Grade', 'BYPL'),
('Banashankari', 'Green Line', 'Elevated', 'BSNK'),
('Benniganahalli', 'Purple Line', 'Elevated', 'JTPM'),
('Challaghatta', 'Purple Line', 'Elevated', 'CLGA'),
('Chickpete', 'Green Line', 'Underground', 'CKPE'),
('Cubbon Park', 'Purple Line', 'Underground', 'CBPK'),
('Dasarahalli', 'Green Line', 'Elevated', 'DSH'),
('Deepanjali Nagar', 'Purple Line', 'Elevated', 'DJNR'),
('Doddakallasandra', 'Green Line', 'Elevated', 'KLPK'),
('Dr. B. R. Ambedkar Station, Vidhana Soudha', 'Purple Line', 'Underground', 'VDSA'),
('Garudacharapalya', 'Purple Line', 'Elevated', 'GDCP'),
('Goraguntepalya', 'Green Line', 'Elevated', 'YPI'),
('Halasuru', 'Purple Line', 'Elevated', 'HLRU'),
('Hoodi', 'Purple Line', 'Elevated', 'DKIA'),
('Hopefarm Channasandra', 'Purple Line', 'Elevated', 'UWVL'),
('Indiranagar', 'Purple Line', 'Elevated', 'IDN'),
('Jalahalli', 'Green Line', 'Elevated', 'JLHL'),
('Jayanagar', 'Green Line', 'Elevated', 'JYN'),
('Jayaprakash Nagar', 'Green Line', 'Elevated', 'JPN'),
('Jnanabharathi', 'Purple Line', 'Elevated', 'BGUC'),
('Kadugodi Tree Park', 'Purple Line', 'Elevated', 'KDGD'),
('Kengeri', 'Purple Line', 'Elevated', 'KGIT'),
('Kengeri Bus Terminal', 'Purple Line', 'Elevated', 'MLSD'),
('Konanakunte Cross', 'Green Line', 'Elevated', 'APRC'),
('Krantivira Sangolli Rayanna Railway Station', 'Purple Line', 'Underground', 'SRCS'),
('Krishna Rajendra Market', 'Green Line', 'Underground', 'KRMT'),
('Krishnarajapura (K.R.Pura)', 'Purple Line', 'Elevated', 'KRAM'),
('Kundalahalli', 'Purple Line', 'Elevated', 'KDNH'),
('Lalbagh', 'Green Line', 'Elevated', 'LBGH'),
('Magadi Road', 'Purple Line', 'Elevated', 'MIRD'),
('Mahakavi Kuvempu Road', 'Green Line', 'Elevated', 'KVPR'),
('Mahalakshmi', 'Green Line', 'Elevated', 'MHLI'),
('Mahatma Gandhi Road', 'Purple Line', 'Elevated', 'MAGR'),
('Mantri Square Sampige Road', 'Green Line', 'Elevated', 'SPGD'),
('Mysuru Road', 'Purple Line', 'Elevated', 'MYRD'),
('Nadaprabhu Kempegowda Station, Majestic', 'Interchange', 'Underground', 'MGST'),
('Nagasandra', 'Green Line', 'Elevated', 'NAGA'),
('Nallurhalli', 'Purple Line', 'Elevated', 'NRHL'),
('National College', 'Green Line', 'Elevated', 'NCOL'),
('Pantharapalya - Nayandahalli', 'Purple Line', 'Elevated', 'NLHI'),
('Pattanagere', 'Purple Line', 'Elevated', 'PTGE'),
('Pattandur Agrahara', 'Purple Line', 'Elevated', 'PTAG'),
('Peenya', 'Green Line', 'Elevated', 'PYAN'),
('Peenya Industry', 'Green Line', 'Elevated', 'PIN'),
('Rajajinagar', 'Green Line', 'Elevated', 'RJNG'),
('Rajarajeshwari Nagar', 'Purple Line', 'Elevated', 'RRNR'),
('Rashtreeya Vidyalaya Road', 'Green Line', 'Elevated', 'RVNL'),
('Sandal Soap Factory', 'Green Line', 'Elevated', 'SDF'),
('Seetharampalya', 'Purple Line', 'Elevated', 'STHY'),
('Silk Institute', 'Green Line', 'Elevated', 'SIKL'),
('Singayyanapalya', 'Purple Line', 'Elevated', 'SGYP'),
('Sir M. Visvesvaraya Station, Central College', 'Purple Line', 'Underground', 'CCOL'),
('South End Circle', 'Green Line', 'Elevated', 'SEC'),
('Sri Balagangadharanatha Swamiji Station, Hosahalli', 'Purple Line', 'Elevated', 'HSH'),
('Sri Sathya Sai Hospital', 'Purple Line', 'Elevated', 'SSSH'),
('Srirampura', 'Green Line', 'Elevated', 'SRPU'),
('Swami Vivekananda Road', 'Purple Line', 'Elevated', 'SVRD'),
('Thalaghattapura', 'Green Line', 'Elevated', 'TGTP'),
('Trinity', 'Purple Line', 'Elevated', 'TNTY'),
('Vajarahalli', 'Green Line', 'Elevated', 'VJHL'),
('Vijayanagar', 'Purple Line', 'Elevated', 'VNGR'),
('Whitefield (Kadugodi)', 'Purple Line', 'Elevated', 'WKGD'),
('Yelachenahalli', 'Green Line', 'Elevated', 'YLHL'),
('Yeshwanthpur', 'Green Line', 'Elevated', 'YSHW');
